### ISSUE TITLE
Duplicated Module after installation

### ISSUE THREAD

**Issue by babbler-eu** [IyiKuyoro/ckeditor5-code-snippet-plugin#2]
Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.
After installing the module in the console this error comes up.

**Comment by IyiKuyoro** [comment]
Hi Raff,

Thanks for reaching out. In order to know how to investigate this, kindly help with the following:

- The list of CKEditor5 packages you have installed
- Your editor setup

Thanks.

**Comment by IyiKuyoro** [comment]
Hi Raff,

Let me also state that you might want to try the code block plugin built by the CKEditor in place of this one. I built this before that was created and have since stopped maintaining it. https://ckeditor.com/docs/ckeditor5/latest/api/code-block.html

But I am still willing to help with the issue.

**Comment by babbler-eu** [comment]
Within the component, I only charge this:
import * as ClassicEditor from '@ ckeditor / ckeditor5-build-classic';
and this is my configuration:
Editor = ClassicEditor;
   editorConfig = {
placeholder: 'Type the content here ...',
extraPlugins: [this.imagePluginFactory],
removePlugins: ['MediaEmbed'],
and this HTML
<ckeditor
                    [editor]="Editor"
                    [config]="editorConfig"     
                    id="description"
                    formControlName="description">
</ckeditor>

**Comment by IyiKuyoro** [comment]
Hi Raff,

I have been able to replicate the issue. I am investigating it currently.

**Comment by IyiKuyoro** [comment]
Hi Raff,

I am sorry to announce to you that you cannot use a **built** editor with plugins out of the box. If you wish to add plugins like this one, you will have to use the editor source or you hack the build a little with instructions found [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build). 

[Here is a reference to the error from the CKEditor documentation](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules).

Let me explain. Plugins contain some source code that has already been included in each build. If you install a build and a plugin together, Webpack complains that some modules already exist. The editor sources, on the other hand, have no duplicate code with plugins. However, with the editor source, you will need to add all the plugins you require manually. See instructions for adding a plugin to the editor source [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build). Also see instructions for setting up your project from the editor source [here](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html).

On my part, I will update the documentation to reflect the fact that you have to either use the editor source for this plugin to work, or you add the plugin to the build before using it.

I will leave this issue open while I update the documentation and for a week after. After that, I will close it and mark as resolved.

Thanks.

**Comment by IyiKuyoro** [comment]
Hi Raff,

Let me also add that you cannot build a custom editor form source yet for Angular. You will need to tinker with the build to use this plugin with your Angular project. [See instructions here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html)

**Comment by babbler-eu** [comment]
Thanks Iyi, for the answers, I understand I have to study quite a bit

**Comment by babbler-eu** [comment]
However, let me say that the CKEditor documentation is very poor, I hope the authors solve this as soon as possible.
